### ISSUE TITLE
Discovery not working on raspberry pi

### ISSUE THREAD

**Issue by acidbath** [n8henrie/fauxmo#5] opened 2016-03-30 02:39 UTC
Sorry to bother you with this, but after several reinstalls I am out of ideas.

I've got a current raspbian jessie installed on my raspberry pi 2 but my amazon echo won't find the virtual wemo devices.
When I was tired of new installations I finally gave it a try on a MacBook and it worked out of the box. The same is true for an Intel NUC running an older Ubuntu - all I needed were your 3 quick installation steps and it worked.
The raspberry pi is online (I've updated the system) and an installed mqtt server (mosquitto) can be reached from all my other machines.

Do you have any idea what might be wrong?

This is the output for a stripped down config.json:
2016-03-30 02:37:42 fauxmo       DEBUG    Listening for UPnP broadcasts
2016-03-30 02:37:42 fauxmo       INFO     Using config: ./config.json
2016-03-30 02:37:42 fauxmo       DEBUG    Using IP address: 192.168.27.52
2016-03-30 02:37:42 fauxmo       DEBUG    Attempting to bind: 192.168.27.52:12345
2016-03-30 02:37:42 fauxmo       DEBUG    UPnP broadcast listener: new device registered
2016-03-30 02:37:42 fauxmo       DEBUG    Device living room light ready on 192.168.27.52:12345
2016-03-30 02:37:42 fauxmo       DEBUG    {'uuid': UUID('e2d2c9d3-176a-410e-aa53-3448f6724c6f'), 'socket': <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=0, laddr=('192.168.27.52', 12345)>, 'port': 12345, 'other_headers': ['X-User-Agent: Fauxmo'], 'action_handler': <fauxmo.handlers.rest.RestApiHandler object at 0x7619b4f0>, 'name': 'living room light', 'server_version': 'Unspecified, UPnP/1.0, Unspecified', 'client_sockets': {}, 'poller': <fauxmo.upnp.Poller object at 0x76290e10>, 'serial': '5ff80a07-b9b1-3f20-b174-1ec5b08d2573', 'listener': <fauxmo.upnp.UpnpBroadcastResponder object at 0x76290d10>, 'ip_address': '192.168.27.52', 'root_url': 'http://{}:{}/setup.xml'}
2016-03-30 02:37:42 fauxmo       DEBUG    Entering main loop (polling)

Thanks a lot!

**Comment by n8henrie** [comment] 2016-03-30 14:16
That looks correct at first glance. Not sure you're having trouble on your Pi2 -- mine was working great. Have you tried watching the debug log while the Echo searches for devices?

Is `12345` the correct port (or just one you masked for posting)?

While Fauxmo is running, in another terminal can you run `sudo lsof -i :12345` to see if the port is being opened properly? (Or if you don't have / don't want to install `lsof`, `sudo netstat -nlp | grep 12345`)

If it looks like Fauxmo is listening properly, you can test the `respond_to_search` function. The easiest way would be to:

1. Open up 2 terminal windows that you can view simultaneously
2. In one window, start Fauxmo in debug mode, e.g. `fauxmo -c config.json -vvv`
3. Once you get to `Entering main loop (polling)`, in the second window, enter the following command:
```bash
echo -e "M-SEARCH\r\nurn:Belkin:device:**" | nc.traditional -u 239.255.255.250 1900
```

This is a quick and dirt mock-up of the UPnP request the Echo sends out. As soon as you send it, you should see a flurry of messages in the Fauxmo window as it responds with the info for each fauxmo "device".

Let me know if this works. If so, it would seem Fauxmo is behaving properly. There have been a number of [intermittent issues](https://github.com/n8henrie/fauxmo/issues/4) getting the Echo to find devices properly -- I often have to go through "device discovery" 3 or 4 times to get all of my devices. Also, you should know that the Echo automatically runs devices discovery every once in a while to make sure it has an up-to-date list of devices.

**Comment by acidbath** [comment] 2016-03-30 15:12
Boy you are quick! :-)

Yepp, 12345 is the port I've used for the first device (a simple copy of your example config.json).

> pi@mqtt-pi:~ $ sudo lsof -i :12345
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
fauxmo  1403   pi    6u  IPv4  16412      0t0  TCP mqtt-pi.fritz.box:12345 (LISTEN)

So fauxmo appears to be listening.

The nc-command results in the following:

> 2016-03-30 14:55:52 fauxmo       DEBUG    Responding to search
2016-03-30 14:55:52 fauxmo       DEBUG    HTTP/1.1 200 OK
CACHE-CONTROL: max-age=86400
DATE: Wed, 30 Mar 2016 14:55:52 GMT
EXT:
LOCATION: http://192.168.27.52:12345/setup.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: d09cbd21-97a3-4bee-bd20-b962194babaf
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:Belkin:device:**
USN: uuid:Socket-1_0-5ff80a07-b9b1-3f20-b174-1ec5b08d2573::urn:Belkin:device:**
X-User-Agent: Fauxmo
2016-03-30 14:56:19 fauxmo       DEBUG    'utf-8' codec can't decode byte 0xa0 in position 389: invalid start byte

So from my beginner's point of view your piece of software does as expected.

I've read through the "intermittent issues" before I created this issue but simply assumed that I had a different problem, because I've had Alexa start the device discovery at least 100 times.
Strange thing is, that fauxmo works flawlessly on both the MacBook as well as the NUC?!

Maybe I'll go for the NUC as my fauxmo server then, I just liked the idea of the RPI because of its low power usage.

Anyway: thanks a lot for your quick response and your useful hints - and sorry for english, I guess I should have paid more attention some twenty years ago in school. :-)

Yours,
Daniel

**Comment by n8henrie** [comment] 2016-03-30 17:23
Your English seems great.

We might be getting somewhere -- it looks like there's an erro[r: `2016-03-30 14:56:19 fauxmo DEBUG 'utf-8' codec can't decode byte 0xa0 in position 389: invalid start byte`

I wonder if the config file you're using on your Pi got an error into it somehow. Can you try to validate `config.json`? For example, `python3 -m json.tool <config.json` . Can you also verify your python version?

Or perhaps, in the Python3 interpreter, ensure that it can read your config as utf8:
```python3
with open("config.json", encoding="utf8") as f:
    print(f.read())
```

**Comment by acidbath** [comment] 2016-03-31 18:21
Both "tests" run through without a problem and I can't find anything unusual at that very position:
> In [9]: with open('config.json', encoding='utf-8') as f:
    data = f.read()
    print('->{}<-'.format(data[388:391]))
   ...:     
->   <-

Around that position there are lots of spaces of an indented line.

And, also quite important to mention, I also get those decoding errors when using the default config file which I retrieved with this command:
> wget

 https://raw.githubusercontent.com/n8henrie/fauxmo/master/config-sample.json

As long as there are only ASCII characters present, there should be no difference between an ASCII and a UTF-8 text file, right?

This morning the discovery worked once which really got my hopes up (though I hadn't changed anything) - but since then Echo won't accept any new devices.

I'll be gone for a couple of days because of work; maybe I'm going to give yet another fresh raspbian install a try next week.

**Comment by n8henrie** [comment] 2016-03-31 21:19
This is very odd. I can `wget` the sample config file and get no such errors. I wonder if it has to do with your system's default language? 

- What do you get when you run `locale -a`?
- What about if you do `file config-sample.json`?
- And again, what python version are you running?

**Comment by acidbath** [comment] 2016-04-01 06:47
pi@mqtt-pi:~ $ locale -a
C
C.UTF-8
de_DE.utf8
en_GB.utf8
POSIX

pi@mqtt-pi:~/fauxmo $ file config-sample.json 
config-sample.json: ASCII text

pi@mqtt-pi:~/fauxmo $ python3 -V
Python 3.4.2

**Comment by n8henrie** [comment] 2016-04-02 20:15
Huh. How about the output of these? Just trying to confirm that fauxmo was installed under / linked to the python 3.5.1 that you're using.
```bash
cat $(command -v fauxmo) | head -1
shebang=$(cat $(command -v fauxmo) | head -1); ${shebang#\#\!} --version
```

**Comment by acidbath** [comment] 2016-04-03 20:34
```
pi@mqtt-pi:~ $ cat $(command -v fauxmo) | head -1

#!/usr/bin/python3

pi@mqtt-pi:~ $ shebang=$(cat $(command -v fauxmo) | head -1); ${shebang#\#\!} --version

Python 3.4.2
```
I'm using python 3.4 which comes with raspbian jessie - might that be an issue?

I'm still away from home, so a fresh raspbian install will have to wait; all I can do right now is vpn into my home network - and I don't want to bother my wife with Alexa constantly telling her, how many smart home devices were found. :-)

**Comment by n8henrie** [comment] 2016-04-04 07:46
No, I'm also running Fauxmo on an RPi 2 running Jessie, which is why this is bothering me. I can't figure out why it's working for me but not for you -- *especially* the weird utf8 codec error.

**Comment by n8henrie** [comment] 2016-04-11 15:05
I've just released Fauxmo 0.3.0, which is a *major* rewrite of much of the internals. It now requires Python >= 3.4.4 (due to #6).

If you're able to install a more recent Python 3 (I've also updated the README with instructions I tested on a fresh Raspbian Jessie install), can you give Fauxmo 0.3.0 a shot and see if this issue persists?

**Comment by acidbath** [comment] 2016-04-13 08:21
Sorry for the delayed response, I was busy at work and came home yesterday evening.

I've reinstalled my RPi and didn't touch anything (keymaps, internationalisation, etc.) -> I don't get the utf-8 error anymore. So maybe it had to do with the locals?!

I also gave your pyenv python 3.5.1 installation a try according to the readme.
Fauxmo starts up without any errors, yet Alexa/Echo won't find any smarthome devices:
```
pi@mqtt-pi:~/fauxmo $ "$(pyenv root)"/versions/3.5.1/bin/fauxmo -c config.json -vvv
2016-04-13 08:07:18 fauxmo       DEBUG    Listening for UPnP broadcasts
2016-04-13 08:07:18 fauxmo       DEBUG    Attempting to get IP address automatically
2016-04-13 08:07:18 fauxmo       DEBUG    Using IP address: 192.168.27.247
2016-04-13 08:07:18 fauxmo       DEBUG    Attempting to bind: 192.168.27.247:12345
2016-04-13 08:07:18 fauxmo       DEBUG    UPnP broadcast listener: new device registered
2016-04-13 08:07:18 fauxmo       DEBUG    Device living room ceiling ready on 192.168.27.247:12345
2016-04-13 08:07:18 fauxmo       DEBUG    {'poller': <fauxmo.upnp.Poller object at 0x76246190>, 'action_handler': <fauxmo.handlers.rest.RestApiHandler object at 0x760d7a50>, 'port': 12345, 'serial': '7323f2e0-7a7a-3678-94ee-0afdc953d59a', 'ip_address': '192.168.27.247', 'listener': <fauxmo.upnp.UpnpBroadcastResponder object at 0x7623c370>, 'name': 'living room ceiling', 'uuid': UUID('83d1fc2d-d206-4d4f-a1b2-60b6b2f7952d'), 'server_version': 'Unspecified, UPnP/1.0, Unspecified', 'socket': <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.27.247', 12345)>, 'client_sockets': {}, 'root_url': 'http://{}:{}/setup.xml', 'other_headers': ['X-User-Agent: Fauxmo']}
2016-04-13 08:07:18 fauxmo       DEBUG    Entering main loop (polling)
```

It responds to the 
```
echo -e "M-SEARCH\r\nurn:Belkin:device:**" | nc.traditional -u 239.255.255.250 1900
```
perfectly fine though.

I guess I'm giving up - we've got a little baby girl and hence my spare time is close to 0. :-)
Yet once again: thanks for your quick reaction and help!

**Comment by n8henrie** [comment] 2016-04-13 11:32
Don't give up quite yet -- those debug messages are from Fauxmo before the recent update. Since you've already installed Python 3.5, you should upgrade to Fauxmo 0.3.0. Most of the server code has been completely rewritten, so if the problem is with Fauxmo I think there is a good chance this would fix it. 

How old is your baby girl? Is she your first? I'm giving my 4 month old boy (my first kiddo) a bottle as I type this out on my phone, so I understand :)

**Comment by acidbath** [comment] 2016-04-13 15:22
I don't have the slightest clue when it comes to using git and installing software from it, so what I did (don't you start laughing! ;-) ) is simply download all your source code files manually and try to fix all the import errors I got.
Not really good at python either, but I finally managed to start cli.py with the python 3.5.1 executable - and it works!

This is what it looks like:
```
pi@mqtt-pi:~/fauxmo/versuch $ /opt/pyenv/versions/3.5.1/bin/python3.5 cli.py -c ../config.json -v
2016-04-13 15:06:11 fauxmo:19       INFO     Fauxmo version 0.3.0
2016-04-13 15:06:12 asyncio:926      INFO     <Server sockets=[<socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.27.247', 12345)>]> is serving
2016-04-13 15:06:12 asyncio:926      INFO     <Server sockets=[<socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.27.247', 12346)>]> is serving
2016-04-13 15:06:13 asyncio:926      INFO     <Server sockets=[<socket.socket fd=10, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.27.247', 12347)>]> is serving
2016-04-13 15:06:13 asyncio:926      INFO     <Server sockets=[<socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.27.247', 12348)>]> is serving
2016-04-13 15:06:13 fauxmo:106      INFO     Starting UDP server
2016-04-13 15:06:42 asyncio:1208     INFO     poll took 29265.283 ms: 1 events
2016-04-13 15:07:01 asyncio:1208     INFO     poll took 18737.174 ms: 1 events
2016-04-13 15:07:16 asyncio:1208     INFO     poll took 15133.369 ms: 1 events
2016-04-13 15:07:23 asyncio:1208     INFO     poll took 6321.112 ms: 1 events
2016-04-13 15:07:35 asyncio:1208     INFO     poll took 12811.817 ms: 1 events
2016-04-13 15:07:35 asyncio:1090     ERROR    Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready() created at /opt/pyenv/versions/3.5.1/lib/python3.5/asyncio/selector_events.py:232>
source_traceback: Object created at (most recent call last):
  File "cli.py", line 32, in <module>
    cli()
  File "cli.py", line 29, in cli
    main(config_path=args.config, verbosity=verbosity)
  File "/home/pi/fauxmo/versuch/fauxmo.py", line 110, in main
    transport, protocol = loop.run_until_complete(listen)
  File "/opt/pyenv/versions/3.5.1/lib/python3.5/asyncio/base_events.py", line 325, in run_until_complete
    self.run_forever()
  File "/opt/pyenv/versions/3.5.1/lib/python3.5/asyncio/base_events.py", line 295, in run_forever
    self._run_once()
  File "/opt/pyenv/versions/3.5.1/lib/python3.5/asyncio/base_events.py", line 1246, in _run_once
    handle._run()
  File "/opt/pyenv/versions/3.5.1/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/opt/pyenv/versions/3.5.1/lib/python3.5/asyncio/selector_events.py", line 232, in add_reader
    handle = events.Handle(callback, args, self)
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.5.1/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/opt/pyenv/versions/3.5.1/lib/python3.5/asyncio/selector_events.py", line 1010, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/home/pi/fauxmo/versuch/protocols.py", line 150, in datagram_received
    msg = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 389: invalid start byte
```
I assume the errors result from me not installing it properly - but I'm getting somewhere.

She's 4 months as well and also my/our first. The impact on one's life is just incredible; everything else just doesn't matter that much anymore (well apart from fauxmo and the raspberry pi of course! ;-) ).

**Comment by n8henrie** [comment] 2016-04-13 19:49
Awesome! One of my first Fauxmo switches was a (dim) light in the baby room controlled by an RF outlet so I could turn it on with my hands full of sleeping baby :)

It's good to know where you're coming from in terms of Python experience -- just a year or two ago I might have done it similarly. I assume you would have installed with `pip` had I remembered to update PyPI -- doh!

It's [uploaded now](https://pypi.python.org/pypi/fauxmo/0.3.0) so you should be able to delete the manually downloaded files and `pip install --upgrade fauxmo`.

**Comment by acidbath** [comment] 2016-04-14 06:51
That's also one of my major use cases - while carrying Mia and a bucket of warm water around to change her diapers leaves me with an insufficient number of free hands to turn on the lights. :-)

So how did you learn all your python and git skills? Did you take courses or is it self-taught from all those tutorials on the web?

Perfect! I just did the installation with pip and it works flawlessly!

Concerning this utf-8 error message:
```
  File "/opt/pyenv/versions/3.5.1/lib/python3.5/site-packages/fauxmo/protocols.py", line 150, in datagram_received
    msg = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 389: invalid start byte
```
Isn't it possible that there are some other network packages floating around in my LAN and one of them isn't utf-8-encoded? Is it possible to peek into the packet and guess its encoding?

Do you want me to close this issue? From my point of view it's solved - the discovery works fine.

So lots of fun with your little boy!
Do you think it's much more difficult to teach a girl to become a nerdy hacker which eventually teaches his old dad all the cool stuff? ;-)

**Comment by n8henrie** [comment] 2016-04-14 15:45
That's great to hear -- makes me so happy to think that this could be helping another new dad at least a little bit!

Yes, pretty much all self taught, though I did to Learn Python the Hard Way early on. I'd probably be much better if I'd taken some classes!

As far as Git, I read [Pro Git](https://git-scm.com/book/en/v2) and found it very helpful to wrap my head around things.

Excellent to hear that discovery is now working. I'm going to close this issue and have opened #7 to address the `UnicodeDecodeError`, which I think we'll also be able to figure out.

Agreed -- I hope that Charlie shared similar maker interested as his dad, can't wait until he's old enough for some nerdy projects together :) Got to head to work!

**Comment by n8henrie** [comment] 2016-04-21 16:17
Resuming conversation [from here](https://github.com/n8henrie/fauxmo/issues/7#issuecomment-212953654  ).

Just to be clear, are you telling the Echo to "find connected devices" or are you clicking the `Discover devices` button in [the web interface](http://alexa.amazon.com/#smart-home)?

Do you see any additional debug output when you do that?

**Comment by acidbath** [comment] 2016-04-21 20:41
I typically tell Alexa to "discover new devices" or press the "Discover devices" button, this doesn't seem to make any difference.

There is no debug output coming from fauxmo when initiating the discovery.

I tried to simply verify whether Alexa is actually sending a discovery request and used this piece of code (found on the web):
```
#!/usr/bin/env python
# coding: utf-8

import socket

UDP_IP = "192.168.27.247"
UDP_PORT = 1900

sock = socket.socket(socket.AF_INET, # Internet
                     socket.SOCK_DGRAM) # UDP
sock.bind((UDP_IP, UDP_PORT))

while True:
    data, addr = sock.recvfrom(1024) # buffer size is 1024 bytes
    print "received message:", data
```
But it doesn't show any output. Shouldn't it display all those messages I see in the fauxmo debug coming from my sonos system?

**Comment by n8henrie** [comment] 2016-04-21 22:20
If you use:

```bash
echo -e '"ssdp:discover"urn:Belkin:device:**' | nc.traditional -u 239.255.255.250 1900
```

does the debug output list all your devices?

**Comment by acidbath** [comment] 2016-04-22 05:35
Yes it does.

Strange thing is: yesterday evening I gave fauxmo another try on my Intel NUC and once again it ran without a hassle. I quit the script and went to bed.
This morning I started fauxmo on the Pi, used your nc-command and initiated another discovery - and all of a sudden all fake wemo switches were simply there?!
Now it could be both: either the fact that I had the same config run on the NUC and Echo somewhat remembered it or it was magically triggered by that nc-command.

**Comment by n8henrie** [comment] 2016-04-22 16:30
Did you "forget" all devices first? Just want to make sure it wasn't the same devices from the NUC yesterday. Having it discover devices on the NUC shouldn't have change how it works with Fauxmo.

The nc command is for simulating a device search by the Echo, but I can't think of any way it would cause the echo to discover devices it wasn't seeing before.

Oddly, I don't see how either of those would change how Fauxmo was working. A third possibility is that it's just coincidental -- for example, my Echo only finds 5 out of my 6 devices with a single search -- I have to do a second search pretty much every time to find that 6th device. With the "old" Fauxmo, it would often find only 1 or 2, sometimes none, and I had to continue to search multiple times until all were found. While the new version seems to be working much better in this regard, I suppose it's possible that you're just experiencing the same thing to a worse degree.

Can you "forget" all devices and re-add the once more, to ensure it's working?

**Comment by acidbath** [comment] 2016-04-24 15:36
I had Echo forget all the NUC devices before starting another search with the pi's fauxmo up and running, yepp. The devices found were definitely coming from the pi (though not all were found, I have to correct my statement from the above post; two were missing which echo found eventually when repeating the search).

So might latency really be a factor here? I've tried fauxmo on the pi several hundred times and the chance of finding devices was very small --- and I've tried fauxmo (also the older versions) on a NUC as well as on a MacBook Air and the search on the echo always succeeded. Maybe the python networking module isn't fast enough (and/or Alexa is somewhat impatient :-) ) on the pi?

**Comment by n8henrie** [comment] 2016-04-24 16:20
Yes, I'm thinking that latency maybe part of the issue, which is one of the big reasons that I did the whole update to use `asyncio`, which seems to have better overall performance for me. I think there's also something else going on though, because I run Fauxmo primarily on a raspberry pi and consistently get five of my six devices discovered on the first try. (By comparison, if I run it on my MacBook air (i7), I get all six discovered.

* Do you have other background processes that you could stop?
* If you run something like `top`, are there any processes that seem to be using up a large amount of the system resources?
* Are you running a GUI on the pi?
* Is the pi connected by ethernet or by Wi-Fi?

**Comment by acidbath** [comment] 2016-04-24 16:37
It's a fresh raspbian jessie installation and I didn't touch anything apart from the fauxmo install of course. I don't use a gui, I always ssh into the pi, which is connected to a gigabit network switch.
And "top" is always on top of "top". ;-)

I am considering to order a pi3 just for testing purposes - another toy I can annoy my wife with. :-)
Or I'll give overclocking a try... but I'd like to be at home for this, so that I can restart it myself. I don't want the previously mentioned woman randomly unplug any cables in my room.

**Comment by n8henrie** [comment] 2016-04-24 18:01
Huh. You shouldn't need a 3, mine ran brilliantly on a 2, and I'd expect it should run fine on a B+ as well. I wonder if it has to do with Ethernet and your switch instead of wifi? I'll experiment. Some switches filter out certain types of broadcasts if I remember correctly, though it wouldn't make sense that it works *sometimes*.

Have you adjusted your memory split? I shift mine all away from video since I also don't use a GUI or the video out (I use the Raspbian Jessie "Lite" as my base installation).

**Comment by acidbath** [comment] 2016-04-24 18:22
Memory split is set to 16, so there should be plenty of RAM available.
Maybe I'll try a wifi dongle when I'm back home, though I don't quite expect it to help; at least latency should get much worse.
If I recall my setup correctly, there's two switches before ethernet reaches the router - maybe this causes trouble to the broadcast messages?! Yet this is also true for the NUC... Anyway I am going to connect the raspi directly to the router which also provides wifi.
But again: I won't be able to give it a try before wednesday.

**Comment by n8henrie** [comment] 2016-04-24 20:05
Huh, I also have mine at 16.
I just tried a RPi model B (not even the B+) connected via ethernet to a switch to the router, and the Echo picked up all 4 devices from the sample config on the first go (after I updated the sample config with 3891d1a2746307485c8a5660723658939047af7c -- whups).

Very odd.

**Comment by n8henrie** [comment] 2016-04-24 22:53
I think we should just take a look at exactly what requests and responses are getting sent and received.

The following commands require some tools you might not have by default; you can get them all with: `sudo apt-get install tcpdump tshark nmap`. Doesn't matter what you choose regarding the wireshark question.

First, get the IP address of your Echo. If you don't know it:
```bash
# Assuming your local subnet is 192.168.27.* , based on posts above
sudo nmap -sP 192.168.27.1/24 | grep -i -B 2 F0:27:2D
```
You should get `Nmap scan report for 192.168.27.XXX` -- your Echo IP address. For the examples below, I'll use `192.168.27.100` as the Echo IP address, and `192.168.27.31` as the Pi's IP address.

Next, we'll check out the info being sent to and from the Echo and Fauxmo. In one window, run Fauxmo in verbose mode. In a second window, run the commands below, and check their output when you tell the Echo to find connected devices.

To get an overview of what's going on, start with `tshark`:

```
sudo tshark -f "host 192.168.27.100" -Y "udp"

# Alternatively, only show the Echo's SEARCH requests:
sudo tshark -f "host 192.168.27.100" -Y "udp contains SEARCH"

# Only show the Fauxmo responses (note still using the Echo's IP):
sudo tshark -f "host 192.168.27.100" -Y "udp contains LOCATION"
```

Example output for the first command, showing a few sets of SSDP SEARCH sent by the Echo followed by 4 responses by Fauxmo (1 for each device in sample config).
```
Capturing on 'eth0'
  1   0.000000 192.168.27.100 -> 239.255.255.250 SSDP 149 M-SEARCH * HTTP/1.1 
  2   0.046414 192.168.27.31 -> 192.168.27.100 SSDP 428 HTTP/1.1 200 OK 
  3   0.064351 192.168.27.31 -> 192.168.27.100 SSDP 428 HTTP/1.1 200 OK 
  4   0.082011 192.168.27.31 -> 192.168.27.100 SSDP 428 HTTP/1.1 200 OK 
  5   0.101093 192.168.27.31 -> 192.168.27.100 SSDP 428 HTTP/1.1 200 OK 
  6   0.104016 192.168.27.100 -> 239.255.255.250 SSDP 149 M-SEARCH * HTTP/1.1 
  7   0.151414 192.168.27.31 -> 192.168.27.100 SSDP 428 HTTP/1.1 200 OK 
  8   0.171049 192.168.27.31 -> 192.168.27.100 SSDP 428 HTTP/1.1 200 OK 
  9   0.191602 192.168.27.31 -> 192.168.27.100 SSDP 428 HTTP/1.1 200 OK 
 10   0.199882 192.168.27.31 -> 192.168.27.100 SSDP 428 HTTP/1.1 200 OK 
 11   0.231841 192.168.27.100 -> 239.255.255.250 SSDP 164 M-SEARCH * HTTP/1.1 
 12   0.333406 192.168.27.100 -> 239.255.255.250 SSDP 164 M-SEARCH * HTTP/1.1 
```

To get a raw look at all the info, use `tcpdump`. I've cleaned up a bunch of garbage in the below output, but you should still be able to recognize each of the critical components.

```bash
sudo tcpdump -s 0 -i eth0 -A host 192.168.27.100
```

This should show a ton of detailed info, including all responses sent to / from the Echo. Replace `etho` with your network interface (check with `ip link`) and `192.168.27.100` with your Echo's IP address.


The output should start with several of the Echo's discovery requests, where you can recognize the `UDP` protocol being sent from the Echo `192.168.27.100` to the network's multicast broadcast `239.255.255.250.1900`, something like:

```
15:48:39.268125 IP 192.168.27.100.50000 > 239.255.255.250.1900: UDP, length 122
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 15
ST: urn:Belkin:device:**
```

Below that, you should see Fauxmo's responses, one for each device in the config:
```
15:48:39.513741 IP 192.168.27.31.1900 > 192.168.27.100.50000: UDP, length 386
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=86400
DATE: Sun, 24 Apr 2016 21:48:39 GMT
EXT:
LOCATION: http://192.168.27.31:12340/setup.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: c66d1ad0-707e-495e-a21a-1d640eed4547
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:Belkin:device:**
USN: uuid:Socket-1_0-2d4ac336-8683-3660-992a-d056b5382a8d::urn:Belkin:device:**
```

Somewhere below that, you'll see the Echo request the `setup.xml`, for each device in the config:

```
15:48:39.761878 IP 192.168.27.100.39720 > 192.168.27.31.12341: Flags [P.], seq 1:68, ack 1, win 274, options [nop,nop,TS val 619246756 ecr 140303456], length 67
GET /setup.xml HTTP/1.1
Host: 192.168.27.31:12341
Accept: */*
```

And somewhere below that, Fauxmo's setup response, for each device in the config:

```
15:48:39.808164 IP 192.168.27.31.12342 > 192.168.27.100.59999: Flags [P.], seq 1:608, ack 68, win 453, options [nop,nop,TS val 140303462 ecr 619246754], length 607
HTTP/1.1 200 OK
CONTENT-LENGTH: 375
CONTENT-TYPE: text/xml
DATE: Sun, 24 Apr 2016 21:48:39 GMT
LAST-MODIFIED: Sat, 01 Jan 2000 00:01:15 GMT
SERVER: Unspecified, UPnP/1.0, Unspecified
X-User-Agent: Fauxmo
CONNECTION: close

<?xml version="1.0"?>
<root>
<device>
<deviceType>urn:Fauxmo:device:controllee:1</deviceType>
<friendlyName>fake hass switch by REST API</friendlyName>
<manufacturer>Belkin International Inc.</manufacturer>
<modelName>Emulated Socket</modelName>
<modelNumber>3.1415</modelNumber>
<UDN>uuid:Socket-1_0-cbc4bc63-e0e2-3a78-8a9f-f0ff7e419b79</UDN>
</device>
</root>
```

Then, to get a *really* close look at a request, well go back to `tshark`. For example, we can add the `-V` flag to get a **ton** more info, and add `-c 1` (count) to limit to capturing a single packet, and further refine the capture filter by specifying that we only want to look at packets sent **from** the Pi **to** the Echo.

```bash
sudo tshark -f "src 192.168.27.31 and dst 192.168.27.100" -c 1 -V
```

At the bottom, you should find the `Hypertext Transfer Protocol` section contains the same `setup.xml` response we found in the `tcpdump` output above.

When you get back in town and have a little time, try the above commands to see what you find. They're a little complicated if you're unfamiliar, but immensely powerful and indispensable for debugging these tricky network issues. If you're not already familiar with them, learning the basics will serve you well in your IoT endeavors!

I'm hoping you can use them to check for a few things:

1. Is the Pi consistently seeing the Echo's `M-SEARCH` requests?
2. Is Fauxmo consistently replying with the `LOCATION` responses?
3. Is the Echo then requesting the `setup.xml` (for each device)?
4. Is Fauxmo consistently replying with the setup info?

If you can confirm that things seem to be working through number 4, then it would seem that Fauxmo is working properly, and the issue would seem to be elsewhere.

**Comment by acidbath** [comment] 2016-04-25 19:55
Wow, I'm impressed - this is a really nice introduction into networking and sniffing. THANKS!
If you should ever come to Germany or I ever visited New Mexico you're definitely invited to a cold beverage. :-)

I've given the first few tshark and tcpdump commands a try, but they don't show any response - whether this is because I'm vpn'ing into my home network or because it is fully switched and the switch doesn't show the pi any of the other packets I can't tell. Though I assume it's the latter.

Maybe a usb wifi dongle isn't that bad an idea at all in order to get rid of the packet filtering.

I'll keep you posted once I sit in front of the pi again...

**Comment by n8henrie** [comment] 2016-04-27 11:46
I'll take you up on that!

That's odd that you're not seeing any responses -- do you VPN to another device on the local network, then SSH to the Pi? Or is the Pi serving the VPN? The latter could be an issue.

I assume you're using the Echo's webapp to trigger the device search?

**Comment by acidbath** [comment] 2016-04-29 10:10
I am close to a mental breakdown. :-)

After I've tried some of the tshark commands at home and they still didn't work (I vpn'ed intro my router when in the hotel room, so I didn't directly log into the pi) I eventually found a 50 foot LAN cable and plugged the pi directly into my main LAN switch and thereby skipping a 5 port TP-Link switch and guess what: everything works like a charm!
The udp packets are received without a loss and the fauxmo devices are discovered as well.
What's really strange about all this is that all my other "office devices" (my iMac as well as a PC and another pi) are also connected to this very 5 port switch and don't show any anomalies (or at least none I've noticed so far). The pi also had perfect network connection (apt-get worked as well as the mqtt server) apart from the udp packet loss. I also gave a different lan cable a try, but it really appears to be the switch which filters out some of the traffic?!

I am really sorry for all your efforts; I should have given this a try way earlier, but with all other services working properly on the pi I just couldn't image this to be a hardware fault. :-(

So let's make it at least two cold beverages then! :-)

**Comment by n8henrie** [comment] 2016-05-01 04:18
I'd say this is surprising given that everything else seems to work with the switch (e.g. your Ubuntu machine), but seems to fit in with the "symptoms" and everything we've discovered through trial and error. How odd!

I wonder if the switch could be changing the source address? Do you see the search broadcasts come through if you look for all UDP packets sent to port 1900? `sudo tcpdump -n udp dst port 1900 -A`

**Comment by acidbath** [comment] 2016-05-01 15:53
It definitely is. I'm currently away from home (again :-( ), but once I get back in on wednesday I'll give it another shot with the long LAN cable...

**Comment by acidbath** [comment] 2016-05-04 08:06
It's me again - back home for a single day. :-/

Anyways... I connected the pi to the 5 port switch again and the tcpdump doesn't show any searches coming from the echo.
What I do see though are broadcasts from my sonos players:
```
07:49:32.434286 IP 192.168.27.218.56112 > 255.255.255.255.1900: UDP, length 180
E.....@.@.]..........0.l..2.M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:schemas-upnp-org:device:ZonePlayer:1
```
I lack the knowledge to understand why some udp packets are transferred and others aren't.

Plugging the pi back into the "main" switch the searches pop up immediately:
```
07:55:42.003917 IP 192.168.27.214.50000 > 239.255.255.250.1900: UDP, length 107
E.....@..............P.l.s. M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 15
ST: urn:Belkin:device:**
```

Nate, you really have done enough (in fact way too much, considering that my hardware is faulty) - thanks again for that!
When packets simply don't reach the pi let alone fauxmo, there's nothing you can do. I just checked the prices for 8 port switches and they're less than 30$ (well, 27€ to be precise, but that's about the same), so I guess I'll upgrade - some additional ports come in handy anyways, though I've won one free port right now. ;-)

**Comment by n8henrie** [comment] 2016-05-04 21:44
Fair enough. It seems like the broadcasts aren't being received at all by the Pi, so while it might be something that could be worked around in software somewhere on the Pi (some kind of firewall filtering things out?) it certainly doesn't seem like something I could change with Fauxmo alone.

Hope you getting it working with the new switch, and feel free to let me know if future issues come up!

**Closed by n8henrie** 2016-05-04 21:44 UTC
