### ISSUE TITLE
No Device found

### ISSUE THREAD

**Issue by hoper83** [n8henrie/fauxmo#92] opened 2019-12-15 11:01 UTC
- Issues not following the template may be closed for that reason alone.
- **Operating system and version**: linux osmc 4.19.55-6-osmc on raspberry
- **Python version**: 3.7.0
- **Fauxmo version** (`fauxmo --version`): 0.4.9
- **Echo device type** (e.g. Echo, Echo Plus, Dot): App Alexa Android 2.2.307833.0
- **[Echo Firmware Version] (https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**: 
Echo input version software 3389728132
## My Issue
I have installed fauxmo on my raspberry, during discovery from Alexa android app the INFO response from fauxmo is "setup.xml requested by Echo" and nothing device is recognized by Alexa App.

## [WHYT](http://mattgemmell.com/what-have-you-tried)
I have search by App android and by input echo.

This is my config.json file:

```json
{
    "FAUXMO": {
        "ip_address": "192.168.1.101"
    },
    "PLUGINS": {
        "SimpleHTTPPlugin": {
            "DEVICES": [
                {
                    "port": 12345,
                    "on_cmd": "http://192.168.1.101:81/on.php",
                    "off_cmd": "http://192.168.1.101:81/off.php ",
                    "method": "GET",
                    "name": "luce soggiorno",
                      }
                  ]
          }      
      }    
}
```	  

---

Please make sure you've taken these steps before submitting a new issue:

- [X] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [X] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [X] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [X] Include your Fauxmo `config.json`
- [X] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] around your debug output and config

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment] 2019-12-15 16:45
Hello,

Sounds like you're trying to use Fauxmo with a non-Echo Alexa device?

If so, please refer to the FAQ: https://github.com/n8henrie/fauxmo/blob/master/README.md#troubleshooting--faq and let me know if I can otherwise be of assistance.

If not, please clarify and include your log as per the issue template.

**Comment by hoper83** [comment] 2019-12-15 18:18
I have tried also with "echo input" and "echo plus".

Below is the setup.xml file:

<root>
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:Belkin:device:controllee:1</deviceType>
<friendlyName>luce soggiorno</friendlyName>
<manufacturer>Belkin International Inc.</manufacturer>
<modelName>Emulated Socket</modelName>
<modelNumber>3.1415</modelNumber>
<UDN>
uuid:Socket-1_0-e098cabc-82ab-32cd-b4f1-ae5f9cddcb9a
</UDN>
<serviceList>
<service>
<serviceType>urn:Belkin:service:basicevent:1</serviceType>
<serviceId>urn:Belkin:serviceId:basicevent1</serviceId>
<controlURL>/upnp/control/basicevent1</controlURL>
<eventSubURL>/upnp/event/basicevent1</eventSubURL>
<SCPDURL>/eventservice.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:metainfo:1</serviceType>
<serviceId>urn:Belkin:serviceId:metainfo1</serviceId>
<controlURL>/upnp/control/metainfo1</controlURL>
<eventSubURL>/upnp/event/metainfo1</eventSubURL>
<SCPDURL>/metainfoservice.xml</SCPDURL>
</service>
</serviceList>
</device>
</root>

Below the logs:

[log.docx](https://github.com/n8henrie/fauxmo/files/3965264/log.docx)

**Comment by n8henrie** [comment] 2019-12-15 18:21
Thanks for the update. So sounds like you're also having this issue with an
actual Echo device.

Please edit your comment to include the log content (edit, then copy and
paste it into your comment). Please surround relevant code output with trip
backticks (```) to mark a codeblock, as per the issue template. See also:
https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

The goal is for other users to be able to find this issue and how we
resolved it by using the search function, which won't work for attachments.

**Comment by n8henrie** [comment] 2019-12-15 18:44
Are you sure the config you posted is correct? Your logs show `
http://192.168.1.101:12340`, but your config says you're using port `12345`.

It's odd that it's not finding anything, I can see that it is finding the
device and querying its state:

```

<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="
http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="
http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetBinaryState
xmlns:u="urn:Belkin:service:basicevent:1"><BinaryState>1</BinaryState></u:GetBinaryState></s:Body></s:Envelope>
```

Are you asking it to "discover devices" from the Echo device? If not, can
you try that?

**Comment by hoper83** [comment] 2019-12-15 19:19
Sorry, the correct config is port 12340.

I searched for devices both with alexa app android and with echo input and with echo plus, but in any case I don't find any new device.

**Comment by n8henrie** [comment] 2019-12-15 19:21
Hmm. I'll see if I can reproduce the issue. Sometimes you have to discover
devices 2 or 3 times in a row before they show up (not sure why).

I can definitely see that it is discovering your device, since it is trying
to query its status. Any chance that you have some kind of a firewall up on
the device hosting the PHP script?

**Comment by hoper83** [comment] 2019-12-15 20:29
I have discovered new devices many time, but every time "nothing". I have also checked that the firewall on distro osmc raspbian is not active. The only firewall that is active is located on my router,  however i have disable it but the result is ever same.
I remain available for any necessary tests.

**Comment by n8henrie** [comment] 2019-12-17 19:08
I cannot replicate the issue. I used essentially your same config and was able to discover `luce soggiorno` on the first try and showed that it worked (successfully tried to call `on.php` and `off.php`).

**Comment by n8henrie** [comment] 2019-12-17 19:09
I'm about to push Fauxmo v0.5.0 -- I don't see why it would change anything, but please try updating and see if you have better luck.

**Comment by n8henrie** [comment] 2019-12-17 22:06
Are you sure your firewall is off? The last part of your log mentions a firewall:

```
NT: urn:schemas-upnp-org:service:WANIPv6FirewallControl:1
```

**Comment by hoper83** [comment] 2019-12-17 22:52
I have disabled firewall and upnp agent on router. Ever same result.
However I have discovered other device Alexa compatible haven't any problems.
Them i have verified that the wemo device in last version needs relative Alexa skill must be actived before for correct recognition.

**Comment by n8henrie** [comment] 2020-01-01 16:52
> Them i have verified that the wemo device in last version needs relative
Alexa skill must be actived before for correct recognition.

Last version of what? I don't think I've ever activated an Alexa skill for
Fauxmo.

I'd like to try a little experiment -- instead of using your PHP script,
can you try running a Python HTTP server on the same device running Fauxmo
and see if that works?

For example, you can run: `python3 -m http.server` and Python will start up
an HTTP server in a local directory, and will print what port it is running
on.

Change your `on_cmd` and `off_cmd` to reflect that location (likely
something like `http://127.0.0.1:8000`) and see if anything changes.

If it is able to see the device, in the terminal running the HTTP server
you should see requests coming in whenever you ask alexa to turn the device
on or off. Let me know if you have any better luck with discovery with this
setup (although there is still room for a firewall issue in between Alexa
and the device running Fauxmo).

You may also experiment with the `use_fake_state` setting introduced in
v0.5.0 (see the readme).

**Comment by n8henrie** [comment] 2020-01-23 15:43
Bump.

This issue is pending a response and is blocked until I have more info. To keep the issue list groomed, I will often close these stalled issues if they go a prolonged time without a response. In this case, I will give it another week or so.

**Comment by n8henrie** [comment] 2020-02-27 15:31
I haven't gotten a reply, so I'm closing this issue as dead. Please feel free to let me know if I should re-open.

**Comment by n8henrie** [comment] 2020-02-27 15:31
I haven't gotten a reply, so I'm closing this issue as dead. Please feel free to let me know if I should re-open.

**Closed** 2020-02-27 15:31 UTC
